### PR TITLE
Add basic Python bindings.

### PR DESCRIPTION
**Pull request by matejak**
Using SWIG.

### CODE REVIEW

**Comment by mpreisler** [comment]
Isn't FindPythonLibs bundled with cmake itself? why bundle it again?

**Comment by matejak** [comment]
I don't know what is or isn't bundled with `cmake`. I gave `cmake` docs a shot, but I wasn't able to find out steps what to do when I want to use another package.

**Comment by mpreisler** [comment]
> I don't know what is or isn't bundled with cmake. I gave cmake docs a shot, but I wasn't able to find out steps what to do when I want to use another package.

Bundling code that ships with vanilla cmake is a bad idea IMO. And I see it's already been done a bunch of times in libswid. I suggest to review and get rid of find modules and other cmake modules that are shipped in cmake itself.

**Comment by matejak** [comment]
Sure, I agree.

**Pull request merged**
